<?php

namespace Database\Seeders;

use App\Models\Pengaduan;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PengaduanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {





        //         $pengaduan = Pengaduan::create([
        //             'judul_pengaduan' => "Kasus Kekerasan Fisik terhadap Balita di Jayapura",
        //             'melapor' => "Famili",
        //             'nama_pelapor' => "Aldi Lawer",
        //             'jk_pelapor' => "Wanita",
        //             'no_hp_pelapor' => '082198213221',
        //                 'informasi_dari' => "Teman/Saudara",
        //                 'alamat_pelapor' => "Entrop",
        //                 'nama_pelapor' => "Helen Watori",
        //                 'jenis_kelamin_korban' => "Wanita",
        //                 'tempat_lahir_korban' => "Jayapura",
        //                 'tanggal_lahir_korban' => date('Y-m-d', strtotime("2000" ."11" . "01")),
        //                 'pekerjaan_korban' => "Siswa",
        //                 'alamat_korban' => "Entrop",
        //                 'agama_korban' => "Kristen Protestan",
        //                 'pendidikan_korban' => "SMP",
        //                 'nik_korban' => "9972198213493",
        //                 'hubungan' => "Suami",
        //                 'jumlah_anak_pria' => 0,
        //                 'jumlah_anak_wanita' => 0,
        //                 'status_pernikahan' => "Belum Menikah",
        //                 'nama_lengkap_pelaku' => "Harry Aris",
        //                 'jenis_kelamin_pelaku' => "Pria",
        //                 'tempat_lahir_pelaku' => "Jayapura",
        //                 'tanggal_lahir_pelaku' => date('Y-m-d', strtotime("1981" ."10" . "01")),
        //                 'agama_pelaku' => "Kristen Protestan",
        //                 'pendidikan_pelaku' => "S1",
        //                 'nik_pelaku' =>"9972198213423",
        //                 'no_hp_pelaku' => '08123456722',
        //                 'pekerjaan_pelaku' => "Pengawai Negeri Sipil pada Dinas Pekerjaan Umum Kota Jayapura",
        //                 'kondisi_fisik' => "Luka-Luka",
        //                 'kondisi_psikis' => "Ketakutan",
        //                 'kondisi_sexual' => "Lain-lain",
        //                 'dampak_fisik' => "Memar-Memar",
        //                 'dampak_psikis' => "Trauma",
        //                 'dampak_sex' => "Lain-lain",
        //                 'dampak_ekonomi' => "Lain-lain",
        //                 'dampak_kesehatan' =>"Lain-lain",
        //                 'dampak_lainnya' => "",
        //                 'kasus_domestik' => 'Kekerasan Fisik',
        //                 'kasus_publik' => 'Penganiyaan',
        //                 'kasus_lainnya' => false,
        //                 'uraian_kejadian' => "Pada awal Januari 2003, seorang balita laki-laki berusia 5 tahun berinisial AL mengalami kekerasan fisik yang dilakukan oleh orang tua angkatnya, pasangan suami istri berinisial JY dan NS, di BTN Organda Padang Bulan, Abepura, Kota Jayapura. Korban mengalami luka-luka di sekujur tubuh, termasuk luka di kepala, bibir, serta patah tulang di tangan dan kaki akibat penganiayaan berulang kali.",
        //                 'user_id' => rand(1, 2),
        //                 'status' => 'Diterima',
        //                 'catatan' => 'Pendampingan yang komprehensif ini bertujuan untuk membantu korban kekerasan psikis pulih secara emosional dan psikologis, serta memastikan mereka dapat tumbuh dan berkembang dalam lingkungan yang aman dan mendukung.',

        //                 'pendamping_id' => 5,
        //                 'created_at' => Carbon::create(2003, 11, 07, 14, 30, 0),
        //                 'updated_at' => Carbon::create(2003, 11, 07, 14, 30, 0),
        //         ]);



        //         $pengaduan = Pengaduan::create([
        //             'judul_pengaduan' => "Kasus Penelantaran Anak di Kota Jayapura",
        //             'melapor' => "Famili",
        //             'nama_pelapor' => "Aldi Lawer",
        //             'jk_pelapor' => "Wanita",
        //             'no_hp_pelapor' => '082198213221',
        //                 'informasi_dari' => "Teman/Saudara",
        //                 'alamat_pelapor' => "Entrop",
        //                 'nama_pelapor' => "Helen Watori",
        //                 'jenis_kelamin_korban' => "Wanita",
        //                 'tempat_lahir_korban' => "Jayapura",
        //                 'tanggal_lahir_korban' => date('Y-m-d', strtotime("2000" ."11" . "01")),
        //                 'pekerjaan_korban' => "Siswa",
        //                 'alamat_korban' => "Entrop",
        //                 'agama_korban' => "Kristen Protestan",
        //                 'pendidikan_korban' => "SMP",
        //                 'nik_korban' => "9972198213493",
        //                 'hubungan' => "Suami",
        //                 'jumlah_anak_pria' => 0,
        //                 'jumlah_anak_wanita' => 0,
        //                 'status_pernikahan' => "Belum Menikah",
        //                 'nama_lengkap_pelaku' => "Harry Aris",
        //                 'jenis_kelamin_pelaku' => "Pria",
        //                 'tempat_lahir_pelaku' => "Jayapura",
        //                 'tanggal_lahir_pelaku' => date('Y-m-d', strtotime("1981" ."10" . "01")),
        //                 'agama_pelaku' => "Kristen Protestan",
        //                 'pendidikan_pelaku' => "S1",
        //                 'nik_pelaku' =>"9972198213423",
        //                 'no_hp_pelaku' => '08123456722',
        //                 'pekerjaan_pelaku' => "Pengawai Negeri Sipil pada Dinas Pekerjaan Umum Kota Jayapura",
        //                 'kondisi_fisik' => "Luka-Luka",
        //                 'kondisi_psikis' => "Ketakutan",
        //                 'kondisi_sexual' => "Lain-lain",
        //                 'dampak_fisik' => "Memar-Memar",
        //                 'dampak_psikis' => "Trauma",
        //                 'dampak_sex' => "Lain-lain",
        //                 'dampak_ekonomi' => "Lain-lain",
        //                 'dampak_kesehatan' =>"Lain-lain",
        //                 'dampak_lainnya' => "",
        //                 'kasus_domestik' => 'Kekerasan Fisik',
        //                 'kasus_publik' => 'Penganiyaan',
        //                 'kasus_lainnya' => false,
        //                 'uraian_kejadian' => "
        // Pada Oktober 20234, UPTD PPA Kota Jayapura menerima laporan dari warga mengenai dua anak bersaudara yang ditelantarkan oleh orang tua mereka di Kelurahan koya barat. Tim UPTD PPA bekerja sama dengan pemerintah setempat untuk menangani kasus tersebut. ",
        //                 'user_id' => rand(1, 2),
        //                 'status' => 'Diterima',
        //                 'pendamping_id' => 7,
        //                 'catatan' => 'Pendampingan yang dilakukan oleh UPTD PPA bertujuan untuk memastikan bahwa hak-hak anak terlindungi dan mereka mendapatkan perawatan serta perhatian yang layak setelah mengalami penelantaran.',
        //                 'created_at' => Carbon::create(2003, 11, 07, 14, 30, 0),
        //                 'updated_at' => Carbon::create(2003, 11, 07, 14, 30, 0),
        //         ]);



        //         $pengaduan = Pengaduan::create([
        //             'judul_pengaduan' => "Kasus Kekerasan Psikis terhadap Anak di Kota Jayapura",
        //             'melapor' => "Famili",
        //             'nama_pelapor' => "Aldi Lawer",
        //             'jk_pelapor' => "Wanita",
        //             'no_hp_pelapor' => '082198213221',
        //                 'informasi_dari' => "Teman/Saudara",
        //                 'alamat_pelapor' => "Entrop",
        //                 'nama_pelapor' => "Helen Watori",
        //                 'jenis_kelamin_korban' => "Wanita",
        //                 'tempat_lahir_korban' => "Jayapura",
        //                 'tanggal_lahir_korban' => date('Y-m-d', strtotime("2000" ."11" . "01")),
        //                 'pekerjaan_korban' => "Siswa",
        //                 'alamat_korban' => "Entrop",
        //                 'agama_korban' => "Kristen Protestan",
        //                 'pendidikan_korban' => "SMP",
        //                 'nik_korban' => "9972198213493",
        //                 'hubungan' => "Suami",
        //                 'jumlah_anak_pria' => 0,
        //                 'jumlah_anak_wanita' => 0,
        //                 'status_pernikahan' => "Belum Menikah",
        //                 'nama_lengkap_pelaku' => "Harry Aris",
        //                 'jenis_kelamin_pelaku' => "Pria",
        //                 'tempat_lahir_pelaku' => "Jayapura",
        //                 'tanggal_lahir_pelaku' => date('Y-m-d', strtotime("1981" ."10" . "01")),
        //                 'agama_pelaku' => "Kristen Protestan",
        //                 'pendidikan_pelaku' => "S1",
        //                 'nik_pelaku' =>"9972198213423",
        //                 'no_hp_pelaku' => '08123456722',
        //                 'pekerjaan_pelaku' => "Pengawai Negeri Sipil pada Dinas Pekerjaan Umum Kota Jayapura",
        //                 'kondisi_fisik' => "Luka-Luka",
        //                 'kondisi_psikis' => "Ketakutan",
        //                 'kondisi_sexual' => "Lain-lain",
        //                 'dampak_fisik' => "Memar-Memar",
        //                 'dampak_psikis' => "Trauma",
        //                 'dampak_sex' => "Lain-lain",
        //                 'dampak_ekonomi' => "Lain-lain",
        //                 'dampak_kesehatan' =>"Lain-lain",
        //                 'dampak_lainnya' => "",
        //                 'kasus_domestik' => 'Kekerasan Fisik',
        //                 'kasus_publik' => 'Penganiyaan',
        //                 'kasus_lainnya' => false,
        //                 'uraian_kejadian' => "Pada tahun 2003, DP3AKB Kota Jayapura menangani 8 kasus kekerasan psikis terhadap anak. Kasus-kasus ini melibatkan tekanan emosional dan psikologis yang signifikan terhadap anak-anak, yang dapat berdampak jangka panjang pada kesehatan mental mereka. Sebagian besar kasus ini ditangani melalui mediasi oleh Pusat Pelayanan Terpadu Pemberdayaan Perempuan dan Anak (P2TP2A) setempat, sementara beberapa lainnya dirujuk ke Unit Pelayanan Perempuan dan Anak (UPPA) Polresta Jayapura Kota untuk penanganan lebih lanjut .",
        //                 'user_id' => rand(1, 2),
        //                 'status' => 'Diterima',
        //                 'pendamping_id' => 6,
        //                 'catatan' => 'Pendampingan yang komprehensif ini bertujuan untuk membantu korban kekerasan psikis pulih secara emosional dan psikologis, serta memastikan mereka dapat tumbuh dan berkembang dalam lingkungan yang aman dan mendukung.',
        //                 'created_at' => Carbon::create(2003, 11, 07, 14, 30, 0),
        //                 'updated_at' => Carbon::create(2003, 11, 07, 14, 30, 0),
        //         ]);


        //         $pengaduan = Pengaduan::create([
        //             'judul_pengaduan' => "Kasus KDRT oleh Oknum Pejabat Kominfo Papua",
        //             'melapor' => "Diri Sendiri",
        //             'nama_pelapor' => "Selviana Kawaitouw",
        //             'jk_pelapor' => "Wanita",
        //             'no_hp_pelapor' => '082198213212',
        //                 'informasi_dari' => "Teman/Saudara",
        //                 'alamat_pelapor' => "Bambu Kuning",
        //                 'nama_pelapor' => "Selviana Kawaitouw",
        //                 'jenis_kelamin_korban' => "Wanita",
        //                 'tempat_lahir_korban' => "Timika",
        //                 'tanggal_lahir_korban' => date('Y-m-d', strtotime("1987" ."10" . "01")),
        //                 'pekerjaan_korban' => "Ibu Rumah Tangga",
        //                 'alamat_korban' => "Bambu Kuning",
        //                 'agama_korban' => "Kristen Protestan",
        //                 'pendidikan_korban' => "SMA",
        //                 'nik_korban' => "9972198213493",
        //                 'hubungan' => "Suami",
        //                 'jumlah_anak_pria' => 0,
        //                 'jumlah_anak_wanita' => 0,
        //                 'status_pernikahan' => "Sudah Menikah",
        //                 'nama_lengkap_pelaku' => "Gerry Riki Yeluan",
        //                 'jenis_kelamin_pelaku' => "Pria",
        //                 'tempat_lahir_pelaku' => "Timika",
        //                 'tanggal_lahir_pelaku' => date('Y-m-d', strtotime("1980" ."10" . "01")),
        //                 'agama_pelaku' => "Kristen Protestan",
        //                 'pendidikan_pelaku' => "S1",
        //                 'nik_pelaku' =>"9972198213421",
        //                 'no_hp_pelaku' => '08123456721',
        //                 'pekerjaan_pelaku' => "Pengawai Negeri Sipil",
        //                 'kondisi_fisik' => "Luka-Luka",
        //                 'kondisi_psikis' => "Ketakutan",
        //                 'kondisi_sexual' => "Lain-lain",
        //                 'dampak_fisik' => "Memar-Memar",
        //                 'dampak_psikis' => "Trauma",
        //                 'dampak_sex' => "Lain-lain",
        //                 'dampak_ekonomi' => "Lain-lain",
        //                 'dampak_kesehatan' =>"Lain-lain",
        //                 'dampak_lainnya' => "",
        //                 'kasus_domestik' => 'Kekerasan Fisik',
        //                 'kasus_publik' => 'Penganiyaan',
        //                 'kasus_lainnya' => false,
        //                 'uraian_kejadian' => "Pada Maret 2004, seorang wanita bernama Selviana Kawaitouw mengalami KDRT berat dari suaminya, GRY, yang merupakan pejabat di Dinas Kominfo Papua. Korban mengalami kekerasan fisik dan verbal selama lebih dari 10 tahun, termasuk ancaman dengan senjata api. Puncak kekerasan terjadi saat korban sedang menjalani perawatan pasca operasi kanker payudara di RSUD Dok II Jayapura. Korban dipukul, ditendang, dan diancam dibunuh oleh pelaku, yang bahkan melakukan video call dengan selingkuhannya sambil menunjukkan aksi kekerasan tersebut . ",
        //                 'user_id' => rand(1, 2),
        //                 'status' => 'Diterima',
        //                 'catatan' => 'Kasus ini menunjukkan pentingnya peran pendamping dalam membantu korban KDRT mendapatkan keadilan dan perlindungan yang layak. Pendampingan yang komprehensif, mulai dari aspek hukum hingga psikologis, sangat krusial dalam proses pemulihan korban dan penegakan hukum terhadap pelaku.',
        //                 'pendamping_id' => 7,
        //                 'created_at' => Carbon::create(2004, 5, 12, 14, 30, 0),
        //                 'updated_at' => Carbon::create(2004, 5, 12, 14, 30, 0),
        //         ]);





        //        $pengaduan = Pengaduan::create([
        //             'judul_pengaduan' => "Kasus KDRT oleh Oknum Pejabat Kominfo Papua",
        //             'melapor' => "Diri Sendiri",
        //             'nama_pelapor' => "Selviana Kawaitouw",
        //             'jk_pelapor' => "Wanita",
        //             'no_hp_pelapor' => '082198213212',
        //                 'informasi_dari' => "Teman/Saudara",
        //                 'alamat_pelapor' => "Bambu Kuning",
        //                 'nama_pelapor' => "Selviana Kawaitouw",
        //                 'jenis_kelamin_korban' => "Wanita",
        //                 'tempat_lahir_korban' => "Timika",
        //                 'tanggal_lahir_korban' => date('Y-m-d', strtotime("1987" ."10" . "01")),
        //                 'pekerjaan_korban' => "Ibu Rumah Tangga",
        //                 'alamat_korban' => "Bambu Kuning",
        //                 'agama_korban' => "Kristen Protestan",
        //                 'pendidikan_korban' => "SMA",
        //                 'nik_korban' => "9972198213493",
        //                 'hubungan' => "Suami",
        //                 'jumlah_anak_pria' => 0,
        //                 'jumlah_anak_wanita' => 0,
        //                 'status_pernikahan' => "Sudah Menikah",
        //                 'nama_lengkap_pelaku' => "Gerry Riki Yeluan",
        //                 'jenis_kelamin_pelaku' => "Pria",
        //                 'tempat_lahir_pelaku' => "Timika",
        //                 'tanggal_lahir_pelaku' => date('Y-m-d', strtotime("1980" ."10" . "01")),
        //                 'agama_pelaku' => "Kristen Protestan",
        //                 'pendidikan_pelaku' => "S1",
        //                 'nik_pelaku' =>"9972198213421",
        //                 'no_hp_pelaku' => '08123456721',
        //                 'pekerjaan_pelaku' => "Pengawai Negeri Sipil",
        //                 'kondisi_fisik' => "Luka-Luka",
        //                 'kondisi_psikis' => "Ketakutan",
        //                 'kondisi_sexual' => "Lain-lain",
        //                 'dampak_fisik' => "Memar-Memar",
        //                 'dampak_psikis' => "Trauma",
        //                 'dampak_sex' => "Lain-lain",
        //                 'dampak_ekonomi' => "Lain-lain",
        //                 'dampak_kesehatan' =>"Lain-lain",
        //                 'dampak_lainnya' => "",
        //                 'kasus_domestik' => 'Kekerasan Fisik',
        //                 'kasus_publik' => 'Penganiyaan',
        //                 'kasus_lainnya' => false,
        //                 'uraian_kejadian' => "Pada Maret 2004, seorang wanita bernama Selviana Kawaitouw mengalami KDRT berat dari suaminya, GRY, yang merupakan pejabat di Dinas Kominfo Papua. Korban mengalami kekerasan fisik dan verbal selama lebih dari 10 tahun, termasuk ancaman dengan senjata api. Puncak kekerasan terjadi saat korban sedang menjalani perawatan pasca operasi kanker payudara di RSUD Dok II Jayapura. Korban dipukul, ditendang, dan diancam dibunuh oleh pelaku, yang bahkan melakukan video call dengan selingkuhannya sambil menunjukkan aksi kekerasan tersebut . ",
        //                 'user_id' => rand(1, 2),
        //                 'status' => 'Diterima',
        //                 'catatan' => 'Kasus ini menunjukkan pentingnya peran pendamping dalam membantu korban KDRT mendapatkan keadilan dan perlindungan yang layak. Pendampingan yang komprehensif, mulai dari aspek hukum hingga psikologis, sangat krusial dalam proses pemulihan korban dan penegakan hukum terhadap pelaku.',
        //                 'pendamping_id' => 7,
        //                 'created_at' => Carbon::create(2004, 5, 12, 14, 30, 0),
        //                 'updated_at' => Carbon::create(2004, 5, 12, 14, 30, 0),
        //         ]);





        //         $pengaduan = Pengaduan::create([
        //             'judul_pengaduan' => "Kasus Kekerasan Seksual oleh Oknum Pejabat di Jayapura",
        //             'melapor' => "Famili",
        //             'nama_pelapor' => "Angel Watori",
        //             'jk_pelapor' => "Wanita",
        //             'no_hp_pelapor' => '082198213211',
        //                 'informasi_dari' => "Teman/Saudara",
        //                 'alamat_pelapor' => "Entrop",
        //                 'nama_pelapor' => "Helen Watori",
        //                 'jenis_kelamin_korban' => "Wanita",
        //                 'tempat_lahir_korban' => "Jayapura",
        //                 'tanggal_lahir_korban' => date('Y-m-d', strtotime("1997" ."10" . "01")),
        //                 'pekerjaan_korban' => "Siswa",
        //                 'alamat_korban' => "Entrop",
        //                 'agama_korban' => "Kristen Protestan",
        //                 'pendidikan_korban' => "SMP",
        //                 'nik_korban' => "9972198213493",
        //                 'hubungan' => "Suami",
        //                 'jumlah_anak_pria' => 0,
        //                 'jumlah_anak_wanita' => 0,
        //                 'status_pernikahan' => "Belum Menikah",
        //                 'nama_lengkap_pelaku' => "Harry Aris Nisga",
        //                 'jenis_kelamin_pelaku' => "Pria",
        //                 'tempat_lahir_pelaku' => "Jayapura",
        //                 'tanggal_lahir_pelaku' => date('Y-m-d', strtotime("1989" ."10" . "01")),
        //                 'agama_pelaku' => "Kristen Protestan",
        //                 'pendidikan_pelaku' => "S1",
        //                 'nik_pelaku' =>"9972198213423",
        //                 'no_hp_pelaku' => '08123456722',
        //                 'pekerjaan_pelaku' => "Pengawai Negeri Sipil pada Dinas Pekerjaan Umum Kota Jayapura",
        //                 'kondisi_fisik' => "Luka-Luka",
        //                 'kondisi_psikis' => "Ketakutan",
        //                 'kondisi_sexual' => "Lain-lain",
        //                 'dampak_fisik' => "Memar-Memar",
        //                 'dampak_psikis' => "Trauma",
        //                 'dampak_sex' => "Lain-lain",
        //                 'dampak_ekonomi' => "Lain-lain",
        //                 'dampak_kesehatan' =>"Lain-lain",
        //                 'dampak_lainnya' => "",
        //                 'kasus_domestik' => 'Kekerasan Fisik',
        //                 'kasus_publik' => 'Penganiyaan',
        //                 'kasus_lainnya' => false,
        //                 'uraian_kejadian' => "Pada November 2004, seorang oknum pejabat berinisial HAN di Jayapura diduga melakukan kekerasan seksual terhadap anak di bawah umur. Korban mengalami kekerasan fisik dan seksual, disertai ancaman pembunuhan oleh pelaku. Pihak kepolisian telah memeriksa tujuh saksi dan melakukan visum serta asesmen psikologis terhadap korban, yang menunjukkan adanya trauma akibat kejadian tersebut. ",
        //                 'user_id' => rand(1, 2),
        //                 'status' => 'Diterima',
        //                 'catatan' => 'Pendampingan ini bertujuan untuk memastikan korban mendapatkan keadilan dan dukungan yang diperlukan dalam proses pemulihan.',
        //                 'pendamping_id' => 6,
        //                 'created_at' => Carbon::create(2004, 11, 07, 14, 30, 0),
        //                 'updated_at' => Carbon::create(2004, 11, 07, 14, 30, 0),
        //         ]);



        // Data array semua kasus
        $kasusList = [
            [
                'judul_pengaduan' => "Kekerasan Fisik terhadap Anak oleh Ayah Kandung",
                'nama_pelapor' => "Yohana Wambrauw",
                'nama_korban' => "Melisa Wambrauw",
                'jenis_kelamin_korban' => "Wanita",
                'tanggal_lahir_korban' => "2015-06-12",
                'tanggal_lahir_pelaku' => "1985-03-20",
                'created_at' => Carbon::create(2004, 6, 5, 14, 30, 0),
            ],
            [
                'judul_pengaduan' => "Kekerasan Psikis terhadap Ibu oleh Suami",
                'nama_pelapor' => "Rita Mambrasar",
                'nama_korban' => "Rita Mambrasar",
                'jenis_kelamin_korban' => "Wanita",
                'tanggal_lahir_korban' => "1990-09-10",
                'tanggal_lahir_pelaku' => "1982-01-15",
                'created_at' => Carbon::create(2004, 6, 20, 10, 45, 0),
            ],
            [
                'judul_pengaduan' => "Pemukulan Anak oleh Tetangga",
                'nama_pelapor' => "Samuel Douw",
                'nama_korban' => "Adrian Douw",
                'jenis_kelamin_korban' => "Pria",
                'tanggal_lahir_korban' => "2012-04-01",
                'tanggal_lahir_pelaku' => "1978-11-22",
                'created_at' => Carbon::create(2004, 7, 2, 9, 15, 0),
            ],
            [
                'judul_pengaduan' => "Pengabaian dan Kekerasan Emosional terhadap Anak oleh Ibu Kandung",
                'nama_pelapor' => "Grace Yoku",
                'nama_korban' => "Dina Yoku",
                'jenis_kelamin_korban' => "Wanita",
                'tanggal_lahir_korban' => "2016-08-30",
                'tanggal_lahir_pelaku' => "1995-07-07",
                'created_at' => Carbon::create(2004, 7, 18, 16, 50, 0),
            ],
            [
                'judul_pengaduan' => "Kasus Kekerasan Seksual oleh Oknum Pejabat di Jayapura",
                'nama_pelapor' => "Angel Watori",
                'nama_korban' => "Helen Watori",
                'jenis_kelamin_korban' => "Wanita",
                'tanggal_lahir_korban' => "1997-10-01",
                'tanggal_lahir_pelaku' => "1989-10-01",
                'created_at' => Carbon::create(2004, 11, 7, 14, 30, 0),
            ],
            [
                'judul_pengaduan' => "Kasus Penganiayaan Anak di Abepura",
                'nama_pelapor' => "David Yoman",
                'nama_korban' => "Lisa Yoman",
                'jenis_kelamin_korban' => "Wanita",
                'tanggal_lahir_korban' => "1998-04-20",
                'tanggal_lahir_pelaku' => "1985-06-15",
                'created_at' => Carbon::create(2004, 12, 1, 10, 15, 0),
            ],
            [
                'judul_pengaduan' => "Kekerasan Dalam Rumah Tangga di Entrop",
                'nama_pelapor' => "Maria Wambrauw",
                'nama_korban' => "Nina Wambrauw",
                'jenis_kelamin_korban' => "Wanita",
                'tanggal_lahir_korban' => "1996-03-10",
                'tanggal_lahir_pelaku' => "1987-07-25",
                'created_at' => Carbon::create(2005, 1, 5, 8, 45, 0),
            ],
            [
                'judul_pengaduan' => "Kasus Pemerkosaan di Waena",
                'nama_pelapor' => "James Mote",
                'nama_korban' => "Sinta Mote",
                'jenis_kelamin_korban' => "Wanita",
                'tanggal_lahir_korban' => "1999-01-17",
                'tanggal_lahir_pelaku' => "1984-02-13",
                'created_at' => Carbon::create(2005, 2, 11, 9, 20, 0),
            ],
            [
                'judul_pengaduan' => "Kekerasan Psikis Anak di Skyline",
                'nama_pelapor' => "Yohana Tabuni",
                'nama_korban' => "Melinda Tabuni",
                'jenis_kelamin_korban' => "Wanita",
                'tanggal_lahir_korban' => "1995-07-14",
                'tanggal_lahir_pelaku' => "1986-05-30",
                'created_at' => Carbon::create(2005, 3, 7, 11, 00, 0),
            ],
            [
                'judul_pengaduan' => "Penganiayaan Berat terhadap Anak di Hamadi",
                'nama_pelapor' => "Ferdinan Wenda",
                'nama_korban' => "Vina Wenda",
                'jenis_kelamin_korban' => "Wanita",
                'tanggal_lahir_korban' => "1994-05-08",
                'tanggal_lahir_pelaku' => "1982-09-12",
                'created_at' => Carbon::create(2005, 4, 2, 13, 45, 0),
            ],
            [
                'judul_pengaduan' => "Eksploitasi Anak untuk Pekerjaan di Pasar Youtefa",
                'nama_pelapor' => "Simon Murib",
                'nama_korban' => "Dina Murib",
                'jenis_kelamin_korban' => "Wanita",
                'tanggal_lahir_korban' => "1993-02-22",
                'tanggal_lahir_pelaku' => "1983-03-10",
                'created_at' => Carbon::create(2005, 5, 16, 14, 10, 0),
            ],
            [
                'judul_pengaduan' => "KDRT Berat di Kotaraja",
                'nama_pelapor' => "Celine Pigai",
                'nama_korban' => "Rosa Pigai",
                'jenis_kelamin_korban' => "Wanita",
                'tanggal_lahir_korban' => "1992-12-12",
                'tanggal_lahir_pelaku' => "1980-08-22",
                'created_at' => Carbon::create(2005, 6, 9, 16, 25, 0),
            ],
            [
                'judul_pengaduan' => "Kasus Pengancaman di Distrik Heram",
                'nama_pelapor' => "Martin Alua",
                'nama_korban' => "Tania Alua",
                'jenis_kelamin_korban' => "Wanita",
                'tanggal_lahir_korban' => "1995-06-19",
                'tanggal_lahir_pelaku' => "1987-11-01",
                'created_at' => Carbon::create(2005, 7, 13, 15, 00, 0),
            ],
            [
                'judul_pengaduan' => "Kasus Kekerasan Seksual di Asrama Mahasiswa",
                'nama_pelapor' => "Samuel Kobogau",
                'nama_korban' => "Veronica Kobogau",
                'jenis_kelamin_korban' => "Wanita",
                'tanggal_lahir_korban' => "1997-11-03",
                'tanggal_lahir_pelaku' => "1988-04-18",
                'created_at' => Carbon::create(2005, 8, 5, 17, 30, 0),
            ],
            [
                'judul_pengaduan' => "KDRT dan Penelantaran Anak di Jayapura Utara",
                'nama_pelapor' => "Elisabeth Degei",
                'nama_korban' => "Sandra Degei",
                'jenis_kelamin_korban' => "Wanita",
                'tanggal_lahir_korban' => "1996-09-29",
                'tanggal_lahir_pelaku' => "1985-01-05",
                'created_at' => Carbon::create(2005, 9, 20, 18, 45, 0),
            ],
            [
                'judul_pengaduan' => "Kekerasan Anak oleh Tenaga Pendidik",
                'nama_pelapor' => "Benny Kogoya",
                'nama_korban' => "Albert Kogoya",
                'jenis_kelamin_korban' => "Pria",
                'tanggal_lahir_korban' => "1994-08-17",
                'tanggal_lahir_pelaku' => "1981-12-25",
                'created_at' => Carbon::create(2005, 10, 11, 8, 00, 0),
            ],
            [
                'judul_pengaduan' => "Eksploitasi Seksual Anak di Jayapura Selatan",
                'nama_pelapor' => "Daniel Murib",
                'nama_korban' => "Joko Murib",
                'jenis_kelamin_korban' => "Pria",
                'tanggal_lahir_korban' => "1993-11-11",
                'tanggal_lahir_pelaku' => "1986-07-01",
                'created_at' => Carbon::create(2005, 11, 6, 9, 15, 0),
            ],
            [
                'judul_pengaduan' => "Kekerasan Seksual dan Psikis oleh Tetangga",
                'nama_pelapor' => "Mika Tabuni",
                'nama_korban' => "Wesly Tabuni",
                'jenis_kelamin_korban' => "Pria",
                'tanggal_lahir_korban' => "1992-02-02",
                'tanggal_lahir_pelaku' => "1980-10-10",
                'created_at' => Carbon::create(2005, 12, 2, 10, 20, 0),
            ],
            [
                'judul_pengaduan' => "Kekerasan Fisik terhadap Anak oleh Ayah Tiri",
                'nama_pelapor' => "Maria Wenda",
                'nama_korban' => "Elisabeth Wenda",
                'tanggal_lahir_korban' => "1998-03-14",
                'jenis_kelamin_korban' => "Wanita",
                'tanggal_lahir_pelaku' => "1970-09-09",
                'created_at' => Carbon::create(2006, 1, 5, 10, 15, 0),
            ],
            [
                'judul_pengaduan' => "Penelantaran Anak oleh Ibu Kandung",
                'nama_pelapor' => "Albertina Kosay",
                'nama_korban' => "Nando Kosay",
                'jenis_kelamin_korban' => "Pria",
                'tanggal_lahir_korban' => "2001-12-02",
                'tanggal_lahir_pelaku' => "1983-06-20",
                'created_at' => Carbon::create(2006, 3, 5, 10, 15, 0),
            ],
            [
                'judul_pengaduan' => "Kekerasan Psikis terhadap Ibu oleh Anak Dewasa",
                'nama_pelapor' => "Yosepha Yikwa",
                'nama_korban' => "Yosepha Yikwa",
                'jenis_kelamin_korban' => "Pria",
                'tanggal_lahir_korban' => "1955-11-30",
                'tanggal_lahir_pelaku' => "1980-08-17",
                'created_at' => Carbon::create(2006, 4, 22, 17, 45, 0),
            ],
            [
                'judul_pengaduan' => "Pemaksaan Kerja terhadap Anak oleh Orang Tua",
                'nama_pelapor' => "Markus Murib",
                'nama_korban' => "Selvi Murib",
                'jenis_kelamin_korban' => "Wanita",
                'tanggal_lahir_korban' => "1999-07-25",
                'tanggal_lahir_pelaku' => "1976-12-12",
                'created_at' => Carbon::create(2006, 5, 10, 13, 00, 0),
            ],
            [
                'judul_pengaduan' => "Kekerasan Fisik terhadap Ibu oleh Suami",
                'nama_pelapor' => "Fransina Tabuni",
                'nama_korban' => "Fransina Tabuni",
                'jenis_kelamin_korban' => "Wanita",
                'tanggal_lahir_korban' => "1978-02-15",
                'tanggal_lahir_pelaku' => "1974-05-05",
                'created_at' => Carbon::create(2006, 6, 19, 07, 40, 0),
            ],
            [
                'judul_pengaduan' => "Pemukulan Anak oleh Paman",
                'nama_pelapor' => "Dorkas Elopere",
                'nama_korban' => "Yohanis Elopere",
                'jenis_kelamin_korban' => "Pria",
                'tanggal_lahir_korban' => "1997-10-10",
                'tanggal_lahir_pelaku' => "1968-04-04",
                'created_at' => Carbon::create(2006, 8, 7, 15, 10, 0),
            ],
            [
                'judul_pengaduan' => "Kekerasan Emosional terhadap Anak oleh Guru Les Privat",
                'nama_pelapor' => "Rina Yoman",
                'nama_korban' => "Alex Yoman",
                'jenis_kelamin_korban' => "Pria",
                'tanggal_lahir_korban' => "1995-06-21",
                'tanggal_lahir_pelaku' => "1972-02-25",
                'created_at' => Carbon::create(2006, 9, 14, 11, 25, 0),
            ],
            [
                'judul_pengaduan' => "Kekerasan terhadap Anak oleh Orang Tua",
                'nama_pelapor' => "Oman Yesi",
                'nama_korban' => "Viktor Yrsu",
                'jenis_kelamin_korban' => "Pria",
                'tanggal_lahir_korban' => "1995-06-21",
                'tanggal_lahir_pelaku' => "1972-02-25",
                'created_at' => Carbon::create(2006, 9, 14, 11, 25, 0),
            ],
        ];

      $userIds = [1, 2, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,18, 19];
$pendampingIds = [5, 6, 7];

$index = 0;

for ($i = 0; $i < 2; $i++) {
    foreach ($userIds as $userId) {
        if (!isset($kasusList[$index])) {
            break; // Jaga-jaga jika data kasus kurang
        }

        $kasus = $kasusList[$index++];

        Pengaduan::create([
            'judul_pengaduan' => $kasus['judul_pengaduan'],
            'melapor' => "Famili",
            'nama_pelapor' => $kasus['nama_pelapor'],
            'jk_pelapor' => "Wanita",
            'no_hp_pelapor' => '08' . rand(1000000000, 9999999999),
            'informasi_dari' => "Teman/Saudara",
            'alamat_pelapor' => "Jayapura",
            'jenis_kelamin_korban' => $kasus['jenis_kelamin_korban'],
            'tempat_lahir_korban' => "Jayapura",
            'tanggal_lahir_korban' => $kasus['tanggal_lahir_korban'],
            'pekerjaan_korban' => "Pelajar",
            'alamat_korban' => "Jayapura",
            'agama_korban' => "Kristen Protestan",
            'pendidikan_korban' => "SMP",
            'nik_korban' => rand(1000000000000, 9999999999999),
            'hubungan' => "Saudara",
            'jumlah_anak_pria' => 0,
            'jumlah_anak_wanita' => 0,
            'status_pernikahan' => "Belum Menikah",
            'nama_lengkap_pelaku' => "Pelaku-" . rand(1, 100),
            'jenis_kelamin_pelaku' => "Pria",
            'tempat_lahir_pelaku' => "Jayapura",
            'tanggal_lahir_pelaku' => $kasus['tanggal_lahir_pelaku'],
            'agama_pelaku' => "Kristen Protestan",
            'pendidikan_pelaku' => "S1",
            'nik_pelaku' => rand(1000000000000, 9999999999999),
            'no_hp_pelaku' => '08' . rand(1000000000, 9999999999),
            'pekerjaan_pelaku' => "PNS",
            'kondisi_fisik' => "Memar",
            'kondisi_psikis' => "Trauma",
            'kondisi_sexual' => "Lain-lain",
            'dampak_fisik' => "Luka",
            'dampak_psikis' => "Trauma Berat",
            'dampak_sex' => "Lain-lain",
            'dampak_ekonomi' => "Tidak Ada",
            'dampak_kesehatan' => "Stress",
            'dampak_lainnya' => "",
            'kasus_domestik' => 'Kekerasan Fisik',
            'kasus_publik' => 'Penganiayaan',
            'kasus_lainnya' => false,
            'uraian_kejadian' => "Kronologi singkat kejadian kekerasan seksual atau fisik terhadap korban.",
            'user_id' => $userId,
            'status' => 'Diterima',
            'catatan' => 'Pendampingan diberikan untuk pemulihan korban.',
            'pendamping_id' => collect($pendampingIds)->random(),
            'created_at' => $kasus['created_at'],
            'updated_at' => $kasus['created_at'],
        ]);
    }
}

    }
}
