<?php

namespace Database\Seeders;

use App\Models\Pengaduan;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PengaduanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $pengaduan = Pengaduan::create([
            'judul_pengaduan' => "Kasus KDRT oleh Oknum Pejabat Kominfo Papua",
            'melapor' => "Diri Sendiri",
            'nama_pelapor' => "Selviana Kawaitouw",
            'jk_pelapor' => 'Wanita',
            'no_hp_pelapor' => '082198213212',
                'informasi_dari' => "Teman/Saudara",
                'alamat_pelapor' => "Bambu Kuning",
                'nama_pelapor' => "Selviana Kawaitouw",
                'jenis_kelamin_korban' => 'Wanita',
                'tempat_lahir_korban' => "Timika",
                'tanggal_lahir_korban' => date('Y-m-d', strtotime("1987" ."10" . "01")),
                'pekerjaan_korban' => "Ibu Rumah Tangga",
                'alamat_korban' => "Bambu Kuning",
                'agama_korban' => "Kristen Protestan",
                'pendidikan_korban' => "SMA",
                'nik_korban' => "9972198213493",
                'hubungan' => "Suami",
                'jumlah_anak_pria' => 0,
                'jumlah_anak_wanita' => 0,
                'status_pernikahan' => "Sudah Menikah",
                'nama_lengkap_pelaku' => "Gerry Riki Yeluan",
                'jenis_kelamin_pelaku' => "Pria",
                'tempat_lahir_pelaku' => "Timika",
                'tanggal_lahir_pelaku' => date('Y-m-d', strtotime("1980" ."10" . "01")),
                'agama_pelaku' => "Kristen Protestan",
                'pendidikan_pelaku' => "S1",
                'nik_pelaku' =>"9972198213421",
                'no_hp_pelaku' => '08123456721',
                'pekerjaan_pelaku' => "Pengawai Negeri Sipil",
                'kondisi_fisik' => "Luka-Luka",
                'kondisi_psikis' => "Ketakutan",
                'kondisi_sexual' => "Lain-lain",
                'dampak_fisik' => "Memar-Memar",
                'dampak_psikis' => "Trauma",
                'dampak_sex' => "Lain-lain",
                'dampak_ekonomi' => "Lain-lain",
                'dampak_kesehatan' =>"Lain-lain",
                'dampak_lainnya' => "",
                'kasus_domestik' => 'Kekerasan Fisik',
                'kasus_publik' => 'Penganiyaan',
                'kasus_lainnya' => false,
                'uraian_kejadian' => "Pada Maret 2004, seorang wanita bernama Selviana Kawaitouw mengalami KDRT berat dari suaminya, GRY, yang merupakan pejabat di Dinas Kominfo Papua. Korban mengalami kekerasan fisik dan verbal selama lebih dari 10 tahun, termasuk ancaman dengan senjata api. Puncak kekerasan terjadi saat korban sedang menjalani perawatan pasca operasi kanker payudara di RSUD Dok II Jayapura. Korban dipukul, ditendang, dan diancam dibunuh oleh pelaku, yang bahkan melakukan video call dengan selingkuhannya sambil menunjukkan aksi kekerasan tersebut . ",
                'user_id' => rand(1, 2),
                'status' => 'Diterima',
                'catatan' => 'Kasus ini menunjukkan pentingnya peran pendamping dalam membantu korban KDRT mendapatkan keadilan dan perlindungan yang layak. Pendampingan yang komprehensif, mulai dari aspek hukum hingga psikologis, sangat krusial dalam proses pemulihan korban dan penegakan hukum terhadap pelaku.',
                'pendamping_id' => 7,
                'created_at' => Carbon::create(2004, 5, 12, 14, 30, 0),
                'updated_at' => Carbon::create(2004, 5, 12, 14, 30, 0),
        ]);





        $pengaduan = Pengaduan::create([
            'judul_pengaduan' => "Kasus Kekerasan Seksual oleh Oknum Pejabat di Jayapura",
            'melapor' => "Famili",
            'nama_pelapor' => "Angel Watori",
            'jk_pelapor' => 'Wanita',
            'no_hp_pelapor' => '082198213211',
                'informasi_dari' => "Teman/Saudara",
                'alamat_pelapor' => "Entrop",
                'nama_pelapor' => "Helen Watori",
                'jenis_kelamin_korban' => 'Wanita',
                'tempat_lahir_korban' => "Jayapura",
                'tanggal_lahir_korban' => date('Y-m-d', strtotime("1997" ."10" . "01")),
                'pekerjaan_korban' => "Siswa",
                'alamat_korban' => "Entrop",
                'agama_korban' => "Kristen Protestan",
                'pendidikan_korban' => "SMP",
                'nik_korban' => "9972198213493",
                'hubungan' => "Suami",
                'jumlah_anak_pria' => 0,
                'jumlah_anak_wanita' => 0,
                'status_pernikahan' => "Belum Menikah",
                'nama_lengkap_pelaku' => "Harry Aris Nisga",
                'jenis_kelamin_pelaku' => "Pria",
                'tempat_lahir_pelaku' => "Jayapura",
                'tanggal_lahir_pelaku' => date('Y-m-d', strtotime("1989" ."10" . "01")),
                'agama_pelaku' => "Kristen Protestan",
                'pendidikan_pelaku' => "S1",
                'nik_pelaku' =>"9972198213423",
                'no_hp_pelaku' => '08123456722',
                'pekerjaan_pelaku' => "Pengawai Negeri Sipil pada Dinas Pekerjaan Umum Kota Jayapura",
                'kondisi_fisik' => "Luka-Luka",
                'kondisi_psikis' => "Ketakutan",
                'kondisi_sexual' => "Lain-lain",
                'dampak_fisik' => "Memar-Memar",
                'dampak_psikis' => "Trauma",
                'dampak_sex' => "Lain-lain",
                'dampak_ekonomi' => "Lain-lain",
                'dampak_kesehatan' =>"Lain-lain",
                'dampak_lainnya' => "",
                'kasus_domestik' => 'Kekerasan Fisik',
                'kasus_publik' => 'Penganiyaan',
                'kasus_lainnya' => false,
                'uraian_kejadian' => "Pada November 2004, seorang oknum pejabat berinisial HAN di Jayapura diduga melakukan kekerasan seksual terhadap anak di bawah umur. Korban mengalami kekerasan fisik dan seksual, disertai ancaman pembunuhan oleh pelaku. Pihak kepolisian telah memeriksa tujuh saksi dan melakukan visum serta asesmen psikologis terhadap korban, yang menunjukkan adanya trauma akibat kejadian tersebut. ",
                'user_id' => rand(1, 2),
                'status' => 'Diterima',
                'catatan' => 'Pendampingan ini bertujuan untuk memastikan korban mendapatkan keadilan dan dukungan yang diperlukan dalam proses pemulihan.',
                'pendamping_id' => 7,
                'created_at' => Carbon::create(2004, 11, 07, 14, 30, 0),
                'updated_at' => Carbon::create(2004, 11, 07, 14, 30, 0),
        ]);



        $pengaduan = Pengaduan::create([
            'judul_pengaduan' => "Kasus Kekerasan Fisik terhadap Balita di Jayapura",
            'melapor' => "Famili",
            'nama_pelapor' => "Aldi Lawer",
            'jk_pelapor' => 'Wanita',
            'no_hp_pelapor' => '082198213221',
                'informasi_dari' => "Teman/Saudara",
                'alamat_pelapor' => "Entrop",
                'nama_pelapor' => "Helen Watori",
                'jenis_kelamin_korban' => 'Wanita',
                'tempat_lahir_korban' => "Jayapura",
                'tanggal_lahir_korban' => date('Y-m-d', strtotime("2000" ."11" . "01")),
                'pekerjaan_korban' => "Siswa",
                'alamat_korban' => "Entrop",
                'agama_korban' => "Kristen Protestan",
                'pendidikan_korban' => "SMP",
                'nik_korban' => "9972198213493",
                'hubungan' => "Suami",
                'jumlah_anak_pria' => 0,
                'jumlah_anak_wanita' => 0,
                'status_pernikahan' => "Belum Menikah",
                'nama_lengkap_pelaku' => "Harry Aris",
                'jenis_kelamin_pelaku' => "Pria",
                'tempat_lahir_pelaku' => "Jayapura",
                'tanggal_lahir_pelaku' => date('Y-m-d', strtotime("1981" ."10" . "01")),
                'agama_pelaku' => "Kristen Protestan",
                'pendidikan_pelaku' => "S1",
                'nik_pelaku' =>"9972198213423",
                'no_hp_pelaku' => '08123456722',
                'pekerjaan_pelaku' => "Pengawai Negeri Sipil pada Dinas Pekerjaan Umum Kota Jayapura",
                'kondisi_fisik' => "Luka-Luka",
                'kondisi_psikis' => "Ketakutan",
                'kondisi_sexual' => "Lain-lain",
                'dampak_fisik' => "Memar-Memar",
                'dampak_psikis' => "Trauma",
                'dampak_sex' => "Lain-lain",
                'dampak_ekonomi' => "Lain-lain",
                'dampak_kesehatan' =>"Lain-lain",
                'dampak_lainnya' => "",
                'kasus_domestik' => 'Kekerasan Fisik',
                'kasus_publik' => 'Penganiyaan',
                'kasus_lainnya' => false,
                'uraian_kejadian' => "Pada awal Januari 2003, seorang balita laki-laki berusia 5 tahun berinisial AL mengalami kekerasan fisik yang dilakukan oleh orang tua angkatnya, pasangan suami istri berinisial JY dan NS, di BTN Organda Padang Bulan, Abepura, Kota Jayapura. Korban mengalami luka-luka di sekujur tubuh, termasuk luka di kepala, bibir, serta patah tulang di tangan dan kaki akibat penganiayaan berulang kali.",
                'user_id' => rand(1, 2),
                'status' => 'Diterima',
                'catatan' => 'Pendampingan yang komprehensif ini bertujuan untuk membantu korban kekerasan psikis pulih secara emosional dan psikologis, serta memastikan mereka dapat tumbuh dan berkembang dalam lingkungan yang aman dan mendukung.',

                'pendamping_id' => 7,
                'created_at' => Carbon::create(2003, 11, 07, 14, 30, 0),
                'updated_at' => Carbon::create(2003, 11, 07, 14, 30, 0),
        ]);



        $pengaduan = Pengaduan::create([
            'judul_pengaduan' => "Kasus Penelantaran Anak di Kota Jayapura",
            'melapor' => "Famili",
            'nama_pelapor' => "Aldi Lawer",
            'jk_pelapor' => 'Wanita',
            'no_hp_pelapor' => '082198213221',
                'informasi_dari' => "Teman/Saudara",
                'alamat_pelapor' => "Entrop",
                'nama_pelapor' => "Helen Watori",
                'jenis_kelamin_korban' => 'Wanita',
                'tempat_lahir_korban' => "Jayapura",
                'tanggal_lahir_korban' => date('Y-m-d', strtotime("2000" ."11" . "01")),
                'pekerjaan_korban' => "Siswa",
                'alamat_korban' => "Entrop",
                'agama_korban' => "Kristen Protestan",
                'pendidikan_korban' => "SMP",
                'nik_korban' => "9972198213493",
                'hubungan' => "Suami",
                'jumlah_anak_pria' => 0,
                'jumlah_anak_wanita' => 0,
                'status_pernikahan' => "Belum Menikah",
                'nama_lengkap_pelaku' => "Harry Aris",
                'jenis_kelamin_pelaku' => "Pria",
                'tempat_lahir_pelaku' => "Jayapura",
                'tanggal_lahir_pelaku' => date('Y-m-d', strtotime("1981" ."10" . "01")),
                'agama_pelaku' => "Kristen Protestan",
                'pendidikan_pelaku' => "S1",
                'nik_pelaku' =>"9972198213423",
                'no_hp_pelaku' => '08123456722',
                'pekerjaan_pelaku' => "Pengawai Negeri Sipil pada Dinas Pekerjaan Umum Kota Jayapura",
                'kondisi_fisik' => "Luka-Luka",
                'kondisi_psikis' => "Ketakutan",
                'kondisi_sexual' => "Lain-lain",
                'dampak_fisik' => "Memar-Memar",
                'dampak_psikis' => "Trauma",
                'dampak_sex' => "Lain-lain",
                'dampak_ekonomi' => "Lain-lain",
                'dampak_kesehatan' =>"Lain-lain",
                'dampak_lainnya' => "",
                'kasus_domestik' => 'Kekerasan Fisik',
                'kasus_publik' => 'Penganiyaan',
                'kasus_lainnya' => false,
                'uraian_kejadian' => "
Pada Oktober 20234, UPTD PPA Kota Jayapura menerima laporan dari warga mengenai dua anak bersaudara yang ditelantarkan oleh orang tua mereka di Kelurahan koya barat. Tim UPTD PPA bekerja sama dengan pemerintah setempat untuk menangani kasus tersebut. ",
                'user_id' => rand(1, 2),
                'status' => 'Diterima',
                'pendamping_id' => 7,
                'catatan' => 'Pendampingan yang dilakukan oleh UPTD PPA bertujuan untuk memastikan bahwa hak-hak anak terlindungi dan mereka mendapatkan perawatan serta perhatian yang layak setelah mengalami penelantaran.',
                'created_at' => Carbon::create(2003, 11, 07, 14, 30, 0),
                'updated_at' => Carbon::create(2003, 11, 07, 14, 30, 0),
        ]);




    }
}
